languages:
   Ruby: true
   JavaScript: true
   Python: false
   PHP: false

exclude_paths:
   - "app/assets/javascripts/modified_cytoscape.js" # can't fix the problems with this for now. we want to get rid of it completely when next cytoscape version stabalized
   - "lib/seek/data/bio_samples.rb" # this is awful and badly affects the score, although it is not currently used directly we cannot remove it.